/**
 * Hand-off Artifact Generator
 *
 * Generates a "Decisions Made" document capturing the user's choices
 * during the Project Generator Wizard. This document is included in
 * the generated ZIP file.
 *
 * Based on Max's insight: The real product is a decision-clarity system
 * that produces knowns, unknowns, and next actions.
 */

import {
  DecisionSnapshot,
  summarizeDecisions,
  getQuestionById,
  QUESTION_CATEGORIES,
} from "./questions";

export type HandoffDocument = {
  markdown: string;
  filename: string;
};

export type ProjectConfig = {
  projectName: string;
  description: string;
  includeADR: boolean;
  includeCI: boolean;
  includeGovernance: boolean;
  includeScaffold: boolean;
  includeAIContext: boolean;
  includeDocker: boolean;
};

export function generateHandoffDocument(
  snapshot: DecisionSnapshot,
  config: ProjectConfig
): HandoffDocument {
  const { knowns, unknowns, nextActions } = summarizeDecisions(snapshot);
  const timestamp = new Date().toISOString().split("T")[0];

  const markdown = `# ${config.projectName} - Decisions Made

> Generated by repOptics Project Generator on ${timestamp}

## Overview

This document captures the decisions made during project setup. It serves as a reference for why the project is structured the way it is.

**Project**: ${config.projectName}
**Description**: ${config.description || "(No description provided)"}

---

## Decisions Captured

${formatDecisionsByCategory(snapshot)}

---

## Summary

### What We Know (Decided)

${knowns.length > 0 ? knowns.map(k => `- ${k}`).join("\n") : "- No decisions captured yet"}

### What We Don't Know (Undecided)

${unknowns.length > 0 ? unknowns.map(u => `- ${u}`).join("\n") : "- All key questions answered"}

### Recommended Next Actions

${nextActions.length > 0 ? nextActions.map(a => `- [ ] ${a}`).join("\n") : "- No specific actions recommended based on current decisions"}

---

## Generated Configuration

The following modules were included in this project:

| Module | Included | Purpose |
|--------|----------|---------|
| ADR Templates | ${config.includeADR ? "Yes" : "No"} | Track architecture decisions |
| CI/CD Pipeline | ${config.includeCI ? "Yes" : "No"} | Automated testing and deployment |
| Governance Files | ${config.includeGovernance ? "Yes" : "No"} | CODEOWNERS, PR templates |
| TypeScript Scaffold | ${config.includeScaffold ? "Yes" : "No"} | Project structure and tooling |
| AI Context | ${config.includeAIContext ? "Yes" : "No"} | AGENTS.md for AI assistants |
| Docker | ${config.includeDocker ? "Yes" : "No"} | Container configuration |

---

## Stack Recommendations

Based on your decisions, here are technology recommendations:

${generateStackRecommendations(snapshot)}

---

## Next Steps

1. **Review this document** - Ensure the captured decisions reflect your intent
2. **Address unknowns** - Make decisions on any open questions
3. **Set up your repository** - Extract the ZIP and initialize git
4. **Configure services** - Set up CI/CD, hosting, database as needed
5. **Document as you go** - Create ADRs for new decisions

---

*This document was generated by [repOptics](https://github.com/bmccall17/repOptics) - a decision-clarity system for developer hygiene.*
`;

  return {
    markdown,
    filename: "DECISIONS.md",
  };
}

function formatDecisionsByCategory(snapshot: DecisionSnapshot): string {
  const sections: string[] = [];

  for (const category of QUESTION_CATEGORIES) {
    const categoryAnswers = snapshot.answers.filter((a) => {
      const q = getQuestionById(a.questionId);
      return q?.category === category.id;
    });

    if (categoryAnswers.length === 0) continue;

    let section = `### ${category.label}\n\n`;

    for (const answer of categoryAnswers) {
      const question = getQuestionById(answer.questionId);
      if (!question) continue;

      section += `**${question.text}**\n\n`;
      section += `_Why it matters:_ ${question.whyItMatters}\n\n`;

      if (answer.selectedOptionIds.length > 0) {
        for (const optionId of answer.selectedOptionIds) {
          const option = question.options.find((o) => o.id === optionId);
          if (!option) continue;

          section += `**Decision:** ${option.label}\n\n`;
          section += `${option.description}\n\n`;

          if (option.consequences.length > 0) {
            section += `_Consequences:_\n`;
            for (const c of option.consequences) {
              section += `- ${c}\n`;
            }
            section += "\n";
          }
        }
      } else {
        section += `**Decision:** Not yet decided\n\n`;
      }

      if (answer.customNote) {
        section += `_Note:_ ${answer.customNote}\n\n`;
      }
    }

    sections.push(section);
  }

  return sections.join("\n---\n\n");
}

function generateStackRecommendations(snapshot: DecisionSnapshot): string {
  const recommendations: string[] = [];

  // Analyze runtime decision
  const runtimeAnswer = snapshot.answers.find(
    (a) => a.questionId === "runtime-type"
  );
  if (runtimeAnswer?.selectedOptionIds.includes("static")) {
    recommendations.push(
      "- **Hosting**: GitHub Pages, Netlify, or Cloudflare Pages (free static hosting)"
    );
  } else if (runtimeAnswer?.selectedOptionIds.includes("serverless")) {
    recommendations.push(
      "- **Hosting**: Vercel or Cloudflare Workers (serverless, scales to zero)"
    );
  } else if (runtimeAnswer?.selectedOptionIds.includes("server")) {
    recommendations.push(
      "- **Hosting**: Render or Railway (always-on server)"
    );
  }

  // Analyze data decision
  const dataAnswer = snapshot.answers.find(
    (a) => a.questionId === "data-storage"
  );
  if (dataAnswer?.selectedOptionIds.includes("database")) {
    recommendations.push(
      "- **Database**: Supabase (Postgres) or PlanetScale (MySQL)"
    );
  } else if (dataAnswer?.selectedOptionIds.includes("local")) {
    recommendations.push(
      "- **Storage**: Browser localStorage or IndexedDB (no server needed)"
    );
  }

  // Analyze auth decision
  const authAnswer = snapshot.answers.find((a) => a.questionId === "data-auth");
  if (authAnswer?.selectedOptionIds.includes("oauth")) {
    recommendations.push("- **Auth**: NextAuth.js or Clerk (OAuth providers)");
  }

  // Analyze cost decision
  const costAnswer = snapshot.answers.find(
    (a) => a.questionId === "cost-budget"
  );
  if (costAnswer?.selectedOptionIds.includes("zero")) {
    recommendations.push(
      "- **Budget Note**: Stick to free tiers - Vercel, Supabase, Cloudflare all have generous free plans"
    );
  }

  // Analyze CI decision
  const ciAnswer = snapshot.answers.find(
    (a) => a.questionId === "guardrails-ci"
  );
  if (
    ciAnswer?.selectedOptionIds.includes("ci") ||
    ciAnswer?.selectedOptionIds.includes("ci-cd")
  ) {
    recommendations.push(
      "- **CI/CD**: GitHub Actions (included with repo, generous free minutes)"
    );
  }

  if (recommendations.length === 0) {
    return "_No specific stack recommendations based on current decisions. Answer more questions for tailored suggestions._";
  }

  return recommendations.join("\n");
}

/**
 * Generate a minimal handoff for cases where the decision wizard wasn't used
 * (backwards compatibility with existing generator flow)
 */
export function generateSimpleHandoff(config: ProjectConfig): HandoffDocument {
  const timestamp = new Date().toISOString().split("T")[0];

  const markdown = `# ${config.projectName} - Project Setup

> Generated by repOptics Project Generator on ${timestamp}

## Overview

**Project**: ${config.projectName}
**Description**: ${config.description || "(No description provided)"}

## Generated Configuration

| Module | Included |
|--------|----------|
| ADR Templates | ${config.includeADR ? "Yes" : "No"} |
| CI/CD Pipeline | ${config.includeCI ? "Yes" : "No"} |
| Governance Files | ${config.includeGovernance ? "Yes" : "No"} |
| TypeScript Scaffold | ${config.includeScaffold ? "Yes" : "No"} |
| AI Context | ${config.includeAIContext ? "Yes" : "No"} |
| Docker | ${config.includeDocker ? "Yes" : "No"} |

## Next Steps

1. Extract the ZIP and initialize git: \`git init\`
2. Install dependencies: \`npm install\` (if scaffold included)
3. Review and customize the generated files
4. Create your first ADR documenting key project decisions

---

*Generated by [repOptics](https://github.com/bmccall17/repOptics)*
`;

  return {
    markdown,
    filename: "DECISIONS.md",
  };
}
